name: lib-invent
channels:
  - rdkit
  - pytorch
  - openeye
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - _tflow_select=2.3.0
  - aiohttp=3.6.2
  - argon2-cffi=20.1.0
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - cachetools=4.1.1
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cmarkgfm=0.4.2
  - colorama=0.4.4
  - cryptography=3.2.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cycler=0.10.0
  - dacite=1.5.1
  - dataclasses=0.7
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dill=0.3.1.1
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.1.1
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jeepney=0.6.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - keyring=21.5.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - multidict=4.7.3
  - multiprocess=0.70.9
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - ninja=1.9.0
  - notebook=6.1.4
  - numpy-base=1.19.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openeye-toolkits=2019.10.2
  - openssl=1.1.1k
  - packaging=20.3
  - pandas=1.0.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathos=0.2.5
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - pkginfo=1.6.1
  - pluggy=0.13.1
  - pox=0.2.7
  - ppft=1.6.6.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.6.0
  - py=1.8.1
  - py-boost=1.67.0
  - py4j=0.10.7
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.7.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.7.0
  - pytz=2019.3
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - rdkit=2020.03.3.0
  - readline=8.0
  - readme_renderer=27.0
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.4.0
  - rsa=4.6
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - secretstorage=3.2.0
  - send2trash=1.5.0
  - setuptools=46.1.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - tensorboard-plugin-wit=1.7.0
  - termcolor=1.1.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.8
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.0.4
  - tqdm=4.43.0
  - traitlets=5.0.5
  - twine=3.2.0
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.4
  - yarl=1.4.2
  - zeromq=4.3.3
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.3.3
    - grpcio==1.32.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.2.1
    - numpy==1.19.5
    - opt-einsum==3.3.0
    - protobuf==3.11.3
    - reinvent-chemistry==0.0.31
    - reinvent-scoring==0.0.20
    - tensorboard==2.4.1
    - tensorflow-estimator==2.4.0
    - werkzeug==1.0.0
    - wheel==0.36.2


